require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/initializers/**/*
    - bin/**/*
    - Guardfile
    - config/environments/*
  SuggestExtensions: false

Rails/FilePath:
  Enabled: false
Style/Documentation:
  Enabled: false
